USE [TopicosEspeciaisDeBancoDeDados]
GO

/****** Object:  Table [dbo].[TB_DVD]    Script Date: 07/04/2015 09:48:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_DVD](
	[cd_dvd] [int] NOT NULL,
	[titulo] [varchar](50) NOT NULL,
	[categoria] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TB_DVD] PRIMARY KEY CLUSTERED 
(
	[cd_dvd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


